### ISSUE TITLE
ElementDrawer for barcodes with interpretation line throwing on OSX-Arm64/.NET 7.0

### ISSUE THREAD

**Issue by christianklauss** [BinaryKits/BinaryKits.Zpl#145]
Environment: OSX (Ventura) on Apple Silicon with .NET 7.0

I've worked on a REST wrapper around some ZPL/Label Printing functionality and I've noticed that using the Viewer library to generate barcodes that contain an interpretation line does not work on my dev machine even if making `libgdiplus` available (with that is running fine with the current /dotnet/sdk:7.0 docker image though, so it's not really a blocker for the project).

```csharp
var labelFont = new SKFont(labelTypeFace, labelFontSize).ToSystemDrawingFont();
int labelHeight = barcode.PrintInterpretationLine ? labelFont.Height : 0;
```
https://github.com/BinaryKits/BinaryKits.Zpl/blob/93caafc2c7a8eb58eb13bb0ce55f7dfe84d27499/src/BinaryKits.Zpl.Viewer/ElementDrawers/Barcode128ElementDrawer.cs#L100

The `labelFont.Height` property is throwing in these cases. I also tried replacing the font loader with a custom one but it didn't change the outcome. Since MS is not pursuing cross-platform support for `System.Common.Drawing` I guess it would require dropping the dependency on that to support this scenario. I guess this might not be worth the effort given that the viewer is fine running in Docker but I just wanted to let you know (thanks for the whole library, was a huge time-saver).

**Comment by primo-ppcg** [comment]
@christianklauss thanks for the feedback.

For most barcode elements, a third-party library is used for rendering [barnhill/barcodelib](https://github.com/barnhill/barcodelib). Unfortunately, this library uses System.Drawing fonts for interpretation lines, rather than SkiaSharp types faces as are used by all other elements.

The resolution for this issue is to remove the dependency, and render barcodes directly from encoded data (which is already done for data matrices and QR codes).
