### ISSUE TITLE
wrong presentation in viwer whith ^FB and ^FH

### ISSUE THREAD

**Issue by yijie0110** [BinaryKits/BinaryKits.Zpl#90]
Hello!
i want to create a label for a Price Tag but when i use 
labelary.com it show right :
![image](https://user-images.githubusercontent.com/37957700/150156731-eeb85b84-e49d-4a0e-aa73-2bd0c3f4ab11.png)
but in BinaryKits.Zpl.Viewer show me :
![image](https://user-images.githubusercontent.com/37957700/150156912-a9ac3d58-53e8-433f-b79c-5d17c1e0fc60.png)
this is zpl text for a label 60*30 mm
`^XA^MMT^PW320^LL0240^LS0
^FT5,75
^A0N,38,31
^FB320,2,0,C
^FDPRODUCT NAME
^FS
^FT29,195
^A0N,71,88
^FH\^FD\15 15.00
^FS
^PQ1,0,1,Y
^XZ`

**Comment by danzk** [comment]
I believe this is because ZPL font 0 is a proprietary font and is replaced by Arial.
You will need to edit the source in [TextFieldElementDrawer.cs](https://github.com/BinaryKits/BinaryKits.Zpl/blob/master/src/BinaryKits.Zpl.Viewer/ElementDrawers/TextFieldElementDrawer.cs) to point to a .ttf of Triumvirate Condensed Bold font.

**Comment by YipingRuan** [comment]
@tinohager

https://github.com/BinaryKits/BinaryKits.Zpl/blob/e7eab3b80a8f193aeea8a14c1685972acb843507/src/BinaryKits.Zpl.Viewer/ElementDrawers/TextFieldElementDrawer.cs#L48
How about I allow user to pass in a font mapping like `{ "0": "FontXXXX", "1": "FontYYYYY" }` ?

**Comment by tinohager** [comment]
I think if we find fonts that are freely available and fit. Nobody is interested in setting fonts manually. At Labelary no one wants to define fonts either. I think for most people our preview fits. For the people who need more can go to Labelary. Otherwise, you have to deal with the issue of how Zebra has defined the fonts and whether they are freely available better. You could also try to ask Zebra about this.

**Comment by YipingRuan** [comment]
@tinohager 
Got your point, there is no way we want to let user upload fronts to our hosting.

Let me add something simple so they can get away with `Arial`, when they host by themselves with other fonts ready.
