### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by johnatwood11** [BinaryKits/BinaryKits.Zpl#91]
I am trying to convert a ZPL text file to an image file and I am using this viewer (https://binarykits-zpl-viewer.azurewebsites.net/) to test against http://labelary.com/viewer.html. Does anyone know if labelary is automatically adding spacing and there is a problem with my code, or if the problem is binarykits? Also, is there any guidance or tutorial on how I could add the Non-supported commands to the project?

binarykits:
![image](https://user-images.githubusercontent.com/76694357/151403017-15d94d28-51c0-4146-896e-1d9a577fa88e.png)
labelary:
![image](https://user-images.githubusercontent.com/76694357/151403535-d08177a0-7f1e-46b8-96a0-0911f98dec2f.png)

ZPL Code:
```
^XA^MNN^LL2923^LH0,0
^TBN,788,30

^A0N,20
^FO16,94^FDOperator:^FS
^AAN,20
^FO96,95^FDBASIC PRODUCTS^FS

^FO0,736^GD3,3,1,w^FS^XZ
```

![image](https://user-images.githubusercontent.com/76694357/151403722-46b2b265-9384-4c0f-ae6a-89f24f0159c7.png)

Thank you

**Comment by tinohager** [comment]
The problem is most likely that we are not using the same fonts. There are no instructions on how to add new commands. If you need a 100% preview I recommend you to use labelary. Or you have to dig deeper into the topic and try to implement it yourself.

https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf
^MN -> Media Tracking (I think this command is unimportant for the preview)
^LL -> Label Length (I think this command is unimportant for the preview)
^TB -> Text Blocks
^GD -> Graphic Diagonal Line
